import mongoose from "mongoose";
import CourseModel from "../models/course.model";
require("dotenv").config();

const courses = [
  {
    id: "c01",
    title: "React - The Complete Guide 2024 (incl. Next.js, Redux)",
    slug: "react-complete-guide",
    thumbnail: "https://i.ibb.co.com/9HXY2g07/React-The-Complete-Guide-2024-incl-Next-js-Redux.png",
    category: "Web Development",
    instructor: { name: "Maximilian Schwarzmüller", role: "Professional Web Developer", avatar: "https://i.pravatar.cc/150?u=max" },
    rating: { score: 4.8, totalReviews: 15420 },
    details: { totalLessons: 240, duration: "48h 30m", level: "All Levels" },
    pricing: { amount: 89.0, currency: "USD", discountPrice: 19.99 },
    isBestseller: true,
  },
  {
    id: "c02",
    title: "The Web Developer Bootcamp 2024",
    slug: "web-developer-bootcamp",
    thumbnail: "https://i.ibb.co.com/tpnRwnTG/The-Web-Developer-Bootcamp.avif",
    category: "Web Development",
    instructor: { name: "Colt Steele", role: "Developer and Teacher", avatar: "https://i.pravatar.cc/150?u=colt" },
    rating: { score: 4.7, totalReviews: 85000 },
    details: { totalLessons: 320, duration: "74h 00m", level: "Beginner" },
    pricing: { amount: 94.0, currency: "USD", discountPrice: 14.99 },
    isBestseller: true,
  },
  {
    id: "c03",
    title: "Advanced CSS and Sass: Flexbox, Grid, Animations",
    slug: "advanced-css-sass",
    thumbnail: "https://i.ibb.co.com/ZR8ThVXQ/advanced-css-sass-animations-thumb.avif",
    category: "Design",
    instructor: { name: "Jonas Schmedtmann", role: "Web Designer", avatar: "https://i.pravatar.cc/150?u=jonas" },
    rating: { score: 4.9, totalReviews: 32000 },
    details: { totalLessons: 120, duration: "28h 10m", level: "Intermediate" },
    pricing: { amount: 79.0, currency: "USD", discountPrice: 12.99 },
    isBestseller: false,
  },
  {
    id: "c04",
    title: "Python for Data Science and Machine Learning",
    slug: "python-data-science",
    thumbnail: "https://i.ibb.co.com/Nd6v6hvj/Python-for-Data-Science-and-Machine-Learning.avif",
    category: "Data Science",
    instructor: { name: "Jose Portilla", role: "Data Scientist", avatar: "https://i.pravatar.cc/150?u=jose" },
    rating: { score: 4.6, totalReviews: 45000 },
    details: { totalLessons: 165, duration: "25h 00m", level: "All Levels" },
    pricing: { amount: 84.0, currency: "USD", discountPrice: 15.99 },
    isBestseller: true,
  },
  {
    id: "c05",
    title: "Ultimate AWS Certified Solutions Architect",
    slug: "aws-solutions-architect",
    thumbnail: "https://i.ibb.co.com/dJmwM2jY/Ultimate-AWS-Certified-Solutions-Architect.avif",
    category: "Cloud Computing",
    instructor: { name: "Stephane Maarek", role: "AWS Expert", avatar: "https://i.pravatar.cc/150?u=steph" },
    rating: { score: 4.7, totalReviews: 120000 },
    details: { totalLessons: 380, duration: "27h 00m", level: "Intermediate" },
    pricing: { amount: 99.0, currency: "USD", discountPrice: 19.99 },
    isBestseller: true,
  },
  {
    id: "c06",
    title: "The Complete Digital Marketing Course",
    slug: "digital-marketing-course",
    thumbnail: "https://i.ibb.co.com/wfsKpSF/The-Complete-Digital-Marketing-Course.avif",
    category: "Marketing",
    instructor: { name: "Rob Percival", role: "Marketing Strategist", avatar: "https://i.pravatar.cc/150?u=rob" },
    rating: { score: 4.5, totalReviews: 28000 },
    details: { totalLessons: 210, duration: "22h 30m", level: "Beginner" },
    pricing: { amount: 69.0, currency: "USD", discountPrice: 11.99 },
    isBestseller: false,
  },
  {
    id: "c07",
    title: "Graphic Design Masterclass - Everything Guide",
    slug: "graphic-design-masterclass",
    thumbnail: "https://i.ibb.co.com/cXb8qDx1/Graphic-Design-Masterclass-Everything-Guide.avif",
    category: "Design",
    instructor: { name: "Lindsay Marsh", role: "Senior Designer", avatar: "https://i.pravatar.cc/150?u=lindsay" },
    rating: { score: 4.8, totalReviews: 18000 },
    details: { totalLessons: 145, duration: "26h 45m", level: "Beginner" },
    pricing: { amount: 74.0, currency: "USD", discountPrice: 13.99 },
    isBestseller: true,
  },
  {
    id: "c08",
    title: "Microsoft Excel - Excel from Beginner to Advanced",
    slug: "excel-mastery",
    thumbnail: "https://i.ibb.co.com/qLG5pNT1/Microsoft-Excel-Excel-from-Beginner-to-Advanced.avif",
    category: "Office Productivity",
    instructor: { name: "Kyle Pew", role: "Microsoft Certified Trainer", avatar: "https://i.pravatar.cc/150?u=kyle" },
    rating: { score: 4.7, totalReviews: 250000 },
    details: { totalLessons: 215, duration: "21h 00m", level: "All Levels" },
    pricing: { amount: 49.0, currency: "USD", discountPrice: 9.99 },
    isBestseller: true,
  },
  {
    id: "c09",
    title: "Complete C# Unity Game Developer 2D",
    slug: "unity-game-dev",
    thumbnail: "https://i.ibb.co.com/mrc0WH3P/Complete-C-Unity-Game-Developer-2-D.avif",
    category: "Game Development",
    instructor: { name: "Rick Davidson", role: "Game Dev Coach", avatar: "https://i.pravatar.cc/150?u=rick" },
    rating: { score: 4.8, totalReviews: 95000 },
    details: { totalLessons: 135, duration: "18h 20m", level: "Beginner" },
    pricing: { amount: 89.0, currency: "USD", discountPrice: 14.99 },
    isBestseller: true,
  },
  {
    id: "c10",
    title: "Java Programming Masterclass for Developers",
    slug: "java-masterclass",
    thumbnail: "https://i.ibb.co.com/23hDSXBZ/Java-Programming-Masterclass-for-Developers.avif",
    category: "Software Engineering",
    instructor: { name: "Tim Buchalka", role: "Java Guru", avatar: "https://i.pravatar.cc/150?u=tim" },
    rating: { score: 4.6, totalReviews: 170000 },
    details: { totalLessons: 420, duration: "80h 00m", level: "All Levels" },
    pricing: { amount: 99.0, currency: "USD", discountPrice: 18.99 },
    isBestseller: true,
  },
  {
    id: "c11",
    title: "Cyber Security: From Zero to Hero",
    slug: "cyber-security-hero",
    thumbnail: "https://i.ibb.co.com/HLp7C2Yc/cyber-security-zero-to-hero-thumb.avif",
    category: "IT & Software",
    instructor: { name: "Nathan House", role: "Security Expert", avatar: "https://i.pravatar.cc/150?u=nathan" },
    rating: { score: 4.7, totalReviews: 54000 },
    details: { totalLessons: 95, duration: "12h 45m", level: "Beginner" },
    pricing: { amount: 64.0, currency: "USD", discountPrice: 10.99 },
    isBestseller: false,
  },
  {
    id: "c12",
    title: "Docker and Kubernetes: The Complete Guide",
    slug: "docker-kubernetes-guide",
    thumbnail: "https://i.ibb.co.com/93pCwjFF/docker-kubernetes-complete-guide-thumb.avif",
    category: "DevOps",
    instructor: { name: "Stephen Grider", role: "Software Engineer", avatar: "https://i.pravatar.cc/150?u=stephen" },
    rating: { score: 4.8, totalReviews: 42000 },
    details: { totalLessons: 260, duration: "22h 00m", level: "Intermediate" },
    pricing: { amount: 89.0, currency: "USD", discountPrice: 16.99 },
    isBestseller: true,
  },
  {
    id: "c13",
    title: "Modern JavaScript From The Beginning",
    slug: "modern-javascript",
    thumbnail: "https://i.ibb.co.com/9HXHHyrv/Modern-Java-Script-From-The-Beginning.webp",
    category: "Web Development",
    instructor: { name: "Brad Traversy", role: "Full Stack Dev", avatar: "https://i.pravatar.cc/150?u=brad" },
    rating: { score: 4.9, totalReviews: 35000 },
    details: { totalLessons: 180, duration: "21h 30m", level: "All Levels" },
    pricing: { amount: 54.0, currency: "USD", discountPrice: 10.99 },
    isBestseller: true,
  },
  {
    id: "c14",
    title: "Figma UI/UX Design Essentials",
    slug: "figma-uiux-essentials",
    thumbnail: "https://i.ibb.co.com/jPfgzrx4/figma-uiux-design-essentials-thumb.avif",
    category: "Design",
    instructor: { name: "Daniel Scott", role: "Adobe Certified Trainer", avatar: "https://i.pravatar.cc/150?u=daniel" },
    rating: { score: 4.8, totalReviews: 21000 },
    details: { totalLessons: 105, duration: "11h 50m", level: "Beginner" },
    pricing: { amount: 79.0, currency: "USD", discountPrice: 12.99 },
    isBestseller: true,
  },
  {
    id: "c15",
    title: "SEO 2024: Complete Training with Blueprints",
    slug: "seo-training-2024",
    thumbnail: "https://i.ibb.co.com/35b4rx64/seo-2026-complete-training-blueprints-thumb.jpg",
    category: "Marketing",
    instructor: { name: "Arun Nagarathanam", role: "SEO Expert", avatar: "https://i.pravatar.cc/150?u=arun" },
    rating: { score: 4.4, totalReviews: 12000 },
    details: { totalLessons: 85, duration: "10h 15m", level: "All Levels" },
    pricing: { amount: 59.0, currency: "USD", discountPrice: 9.99 },
    isBestseller: false,
  },
  {
    id: "c16",
    title: "Node.js, Express & MongoDB Dev to Deployment",
    slug: "nodejs-express-mongodb",
    thumbnail: "https://i.ibb.co.com/DP9vjWXX/Node-js-Express-Mongo-DB-Dev-to-Deployment.webp",
    category: "Web Development",
    instructor: { name: "Brad Traversy", role: "Full Stack Dev", avatar: "https://i.pravatar.cc/150?u=brad2" },
    rating: { score: 4.8, totalReviews: 29000 },
    details: { totalLessons: 140, duration: "12h 00m", level: "Intermediate" },
    pricing: { amount: 69.0, currency: "USD", discountPrice: 11.99 },
    isBestseller: true,
  },
  {
    id: "c17",
    title: "Machine Learning A-Z: Hands-On Python & R",
    slug: "machine-learning-az",
    thumbnail: "https://i.ibb.co.com/fz4LJGVt/machine-learning-az-python-r-hands-on-thumb.webp",
    category: "Data Science",
    instructor: { name: "Kirill Eremenko", role: "Data Scientist", avatar: "https://i.pravatar.cc/150?u=kirill" },
    rating: { score: 4.6, totalReviews: 160000 },
    details: { totalLessons: 280, duration: "44h 30m", level: "All Levels" },
    pricing: { amount: 94.0, currency: "USD", discountPrice: 17.99 },
    isBestseller: true,
  },
  {
    id: "c18",
    title: "Generative AI & Prompt Engineering",
    slug: "generative-ai-prompt-engineering",
    thumbnail: "https://i.ibb.co.com/SS4K8QC/generative-ai-prompt-engineering.avif",
    category: "AI",
    instructor: { name: "AI Expert", role: "Prompt Engineer", avatar: "https://i.pravatar.cc/150?u=ai" },
    rating: { score: 4.7, totalReviews: 8000 },
    details: { totalLessons: 90, duration: "9h 00m", level: "Beginner" },
    pricing: { amount: 49.0, currency: "USD", discountPrice: 12.99 },
    isBestseller: true,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.DB_URL!, { dbName: "lms" });
    console.log("✅ Connected to MongoDB");

    await CourseModel.deleteMany({});
    console.log("🗑️ Cleared existing courses");

    await CourseModel.insertMany(courses);
    console.log(`✅ Inserted ${courses.length} courses`);

    await mongoose.disconnect();
    console.log("✅ Done!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed error:", error);
    process.exit(1);
  }
}

seed();